---
# Docker Compose 2.4 is for local development
# https://www.heroku.com/podcasts/codeish/57-discussing-docker-containers-and-kubernetes-with-a-docker-captain - Source on that.
version: '2.4'

x-app: &app
  image: middleman:0.1.0
  mem_limit: 512m
  tmpfs:
    - /tmp
  build:
    context: .
    dockerfile: Dockerfile
    target: development
  volumes:
    - .:/usr/src/app:cached
    - bundler:/usr/local/bundle:delegated
    - node_modules:/usr/src/app/node_modules:delegated

services:
  web:
    <<: *app
    command: >
      bash -c "bundle check || bundle install &&
      yarn install --check-files &&
      bundle exec middleman server -p 3000"
    ports:
      - "${PORT:-3000}:3000"

volumes:
  bundler:
  node_modules: 
